version: '3.8'
services:
  testing:
    build:
      context: .
    environment:
      SERVER: http://monitoring:1157
    depends_on:
      monitoring:
        condition: service_healthy
    links:
      - monitoring
  monitoring:
    image: monitoring
    ports:
      - 1157:1157
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/1157"]
      interval: 3s
      timeout: 60s
      retries: 10
      start_period: 3s
